include: "rules/common.smk"
include: "rules/read_processing.smk"
include: "rules/assembly.smk"
include: "rules/qc.smk"

rule all:
    input:
        multiqc_report="results/multiqc/multiqc_report.html",
        genomes=expand(["results/{id}/{id}.shiver_assembly.fasta"], id=IDS)
